class AddDefaultDataCoas < ActiveRecord::Migration[5.0]
  def up
    categories = [{"id":1,"name":"Cash","parent_id":"","classification":1},{"id":2,"name":"Receivables","parent_id":"","classification":1},{"id":3,"name":"Inventories","parent_id":"","classification":1},{"id":4,"name":"Fixed Assets","parent_id":"","classification":1},{"id":5,"name":"Other Assets","parent_id":"","classification":1},{"id":6,"name":"Current Liabilities","parent_id":"","classification":2},{"id":7,"name":"Long Term Liabilities","parent_id":"","classification":2},{"id":8,"name":"Equity","parent_id":"","classification":3},{"id":9,"name":"Stock","parent_id":"","classification":3},{"id":10,"name":"Prive","parent_id":"","classification":3},{"id":11,"name":"Dividends","parent_id":"","classification":3},{"id":12,"name":"Sales","parent_id":"","classification":4},{"id":13,"name":"Core Business Revenue","parent_id":"","classification":4},{"id":14,"name":"Outside Core Business Revenue","parent_id":"","classification":4},{"id":15,"name":"Indirect Selling Expenses","parent_id":"","classification":5},{"id":16,"name":"Business Cost","parent_id":"","classification":5},{"id":17,"name":"Outside Business Cost","parent_id":"","classification":5},{"id":18,"name":"Interest Expenses","parent_id":"","classification":5},{"id":19,"name":"Income Tax Expenses","parent_id":"","classification":5}]
    AccountingAccountCategory.create(categories)

    coas = [{"id":1,"code":51201,"parent_id":"","description":"Biaya Pegawai","classification":5,"category_id":16},{"id":2,"code":51202,"parent_id":"","description":"Biaya Listrik","classification":5,"category_id":16},{"id":3,"code":11101,"parent_id":"","description":"Cash","classification":1,"category_id":1},{"id":4,"code":11102,"parent_id":"","description":"Petty Cash","classification":1,"category_id":1},{"id":5,"code":11103,"parent_id":"","description":"Cash B","classification":1,"category_id":1},{"id":6,"code":12101,"parent_id":"","description":"Piutang Usaha","classification":1,"category_id":2},{"id":7,"code":13101,"parent_id":"","description":"Persediaan Barang Dagang","classification":1,"category_id":3},{"id":8,"code":41101,"parent_id":"","description":"Penjualan Barang Dagang","classification":4,"category_id":12},{"id":9,"code":41102,"parent_id":"","description":"Penjualan Divisi Case","classification":4,"category_id":12},{"id":10,"code":41103,"parent_id":"","description":"Penjualan Divisi Guitar","classification":4,"category_id":12},{"id":11,"code":51203,"parent_id":"","description":"Biaya Depresiasi Mesin","classification":5,"category_id":16},{"id":12,"code":41104,"parent_id":"","description":"Penjualan Divisi Service","classification":4,"category_id":12},{"id":13,"code":51301,"parent_id":"","description":"Biaya Selisih Kurs","classification":5,"category_id":17},{"id":14,"code":51204,"parent_id":"","description":"Biaya Bahan Baku","classification":5,"category_id":16},{"id":15,"code":51205,"parent_id":"","description":"Biaya Bahan Penolong","classification":5,"category_id":16},{"id":16,"code":31101,"parent_id":"","description":"Modal Hanung Squad","classification":3,"category_id":8},{"id":17,"code":31301,"parent_id":"","description":"Prive Hanung","classification":3,"category_id":10},{"id":18,"code":21101,"parent_id":"","description":"Utang Usaha","classification":2,"category_id":6},{"id":19,"code":21102,"parent_id":"","description":"Utang Gaji","classification":2,"category_id":6},{"id":20,"code":21103,"parent_id":"","description":"Utang Listrik","classification":2,"category_id":6},{"id":21,"code":15101,"parent_id":"","description":"Akumulasi Penyusutan Mesin","classification":1,"category_id":5},{"id":22,"code":51206,"parent_id":"","description":"Biaya Pengiriman","classification":5,"category_id":16},{"id":23,"code":51207,"parent_id":"","description":"Potongan Penjualan","classification":5,"category_id":16}]
    AccountingAccount.create(coas)
  end
end
